### ISSUE TITLE
Can't find GetInjectedThreads?

### ISSUE THREAD

**Issue by hayasec** [Apr4h/CobaltStrikeScan#1]
![image](https://user-images.githubusercontent.com/36404088/94383491-cd779d80-0172-11eb-9d3b-3f122175f605.png)

Folder GetInjectedThreads is empty.

**Comment by Apr4h** [comment]
My apologies, I thought I could reference my other repo - GetInjectedThreads - and that the code would be included when this repo was cloned. Ill fix this within the next few hours.

**Comment by hayasec** [comment]
thx, got it.

I have decompiled the exe binary to got getInjectedthreads.dll for the time being.
