### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by chapinb** [Apr4h/CobaltStrikeScan#14]
Hi there! Would you consider adding a license to the code to provide contributors and users information about the acceptable terms of usage?

There are a lot of options, the site https://choosealicense.com/licenses/ provides a number of choices, though if you are considering something permissible that can help us all continue to combat threat actors I would suggest evaluating any of the following:

1. Boost Software License 1.0 https://choosealicense.com/licenses/bsl-1.0/
1. MIT https://choosealicense.com/licenses/mit/

If you would prefer no license, you can make it public domain, though it would help to include a license file similar to the one shown here: https://choosealicense.com/licenses/unlicense/

**Comment by Apr4h** [comment]
Thanks for the suggestion :) I've chosen to add the MIT license to the repository.
