### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Ryan-8023** [Apr4h/CobaltStrikeScan#4]
未经处理的异常:  System.MissingMethodException: 找不到方法:“Boolean System.Console.get_IsOutputRedirected()”。

Server stack trace:
   在 CommandLine.ParserSettings.GetWindowWidth()
   在 CommandLine.Parser.<>c.<.cctor>b__20_0()
   在 System.Lazy`1.CreateValue()

Exception rethrown at [0]:
   在 CommandLine.ParserSettings.GetWindowWidth()
   在 CommandLine.Parser.<>c.<.cctor>b__20_0()
   在 System.Lazy`1.CreateValue()
   在 System.Lazy`1.LazyInitValue()
   在 ConsoleUI.Program.Main(String[] args)

**Comment by Apr4h** [comment]
Hi, Sorry I don't speak Chinese but even after using Google Translate, I still need some more information to understand how this exception occurred. Can you provide some more context? Were you trying to use Chinese characters as arguments to the program? Did a particular command-line option trigger this exception?

**Comment by Apr4h** [comment]
Closing this issue because:

- I don't have enough information
- I can't replicate the exception
- You haven't responded
