### ISSUE TITLE
cs4.2 Scanning processes for injected threads ?

### ISSUE THREAD

**Issue by badboycxcc** [Apr4h/CobaltStrikeScan#7]
![image](https://user-images.githubusercontent.com/72059221/110586511-52002a80-81ad-11eb-9ec7-7d81d6d8cbd5.png)
Listening is http
no Malleable-C2-Profiles

**Comment by Apr4h** [comment]
Please provide the details included in this repo's bug report template so that I have enough information to triage the issue. 

It would also be helpful if you could provide a memory dump of the process containing the loaded beacon. You could use Sysinternals' Procdump like so: `procdump.exe -ma <PID>`. 

My first suggestion is to try downloading and using [the latest version](https://github.com/Apr4h/CobaltStrikeScan/releases/tag/1.0.1) of the tool

**Comment by badboycxcc** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            The problem has been solved, can only analyze the process after cobaltstrike injection? Does not support analysis of beacon programs?
        
    
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                badboycxcc
                            
                    
                        
                            
                                    badboycxcc@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/10/2021 15:18，Apra<notifications@github.com> wrote： 



Please provide the details included in this repo's bug report template so that I have enough information to triage the issue.
It would also be helpful if you could provide a memory dump of the process containing the loaded beacon. You could use Sysinternals' Procdump like so: procdump.exe -ma <PID>.
My first suggestion is to try downloading and using the latest version of the tool

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
