### ISSUE TITLE
"libyaraNET" Missing

### ISSUE THREAD

**Issue by Salmonhunter5000** [Apr4h/CobaltStrikeScan#9]
Hi,
I am having difficulties creating the program with msbuild. I get the error message that when CobaltStrikeConfigParser.csproj is created, "libyaraNET" cannot be found. The process is then canceled. What do I have to install so that the creation of the program works.

I'm using a Windows 10 system with Visual Studio Build Tools 2019 (Version 16.9.4) and .NET Framework Versions 4-4.6.1

**Comment by Salmonhunter5000** [comment]
Sorry found the error myself...

**Comment by theonlykernel** [comment]
@Apr4h I have this same issue - what is the solution?

**Comment by Apr4h** [comment]
> @Apr4h I have this same issue - what is the solution?

If you have the solution open in Visual Studio, make sure you have an x64 build option selected rather than 'Any CPU' as LibYara.NET is only 64bit. Otherwise you will probably need to manually edit the solution / project files to ensure that you're building as x64 rather than 'Any CPIU'. That should fix your issue but let me know if it doesn't.

**Comment by dimante** [comment]
I had to go get the libyara.net dll to get this to work.  It seems its missing form your project.

**Comment by theonlykernel** [comment]
@dimante same situation here.

@Apr4h can you update the release to include the libtaraNET dll? I'm not compiling from source but had to install it via the dotnet CLI.

Thx!

**Comment by Apr4h** [comment]
Thanks for the info. Hopefully the most recent commit: 42874a61baeddc1134110b9238b771aed14b73c1 should fix the issue.

**Comment by theonlykernel** [comment]
> Thanks for the info. Hopefully the most recent commit: [42874a6](https://github.com/Apr4h/CobaltStrikeScan/commit/42874a61baeddc1134110b9238b771aed14b73c1) should fix the issue.

thanks, will releases be updated soon?
